[package]
name = "eccl_raw"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Low level bindings to the TOPS ECCL API"
readme = "../../README.md"

[dependencies]
libloading = "0.8.5"
tops_raw = { path = "../tops_raw", version = "0.1.1"}